function data = separateRows(raw_data)

vn1 = ["record_id" "Duplicate_1" "Duplicate_2" "Duplicate_3" ...
    "redcap_event_name" "redcap_survey_identifier" "group" ...
    "group_value" "list_discipline" "list_year_enrolled" ...
    "student_survey_timestamp" "advanced" "milestones_cogsci" ...
    "milestones_psysci" "enjoy" "good" "nonexperts" "discouraged" ...
    "writers_block" "inspired" "cant_start" "rejection" "rcv_fdbk" ...
    "gv_fdbk" "timeblock" "hours" "conference_submit" ...
    "conference_accept" "perma_hap"];

vn2 = ["record_id" "Duplicate_1" "Duplicate_2" "Duplicate_3" ...
    "redcap_event_name" "redcap_survey_identifier" "group" ...
    "group_value" "list_discipline" "list_year_enrolled" ...
    "student_survey_new_participant_timestamp" "advanced_nu" ...
    "milestones_cogsci_nu" "milestones_psysci_nu" "enjoy_nu" ...
    "good_nu" "nonexperts_nu" "discouraged_nu" "writers_block_nu" ...
    "inspired_nu" "cant_start_nu" "rejection_nu" "rcv_fdbk_nu" ...
    "gv_fdbk_nu" "timeblock_j22_nu" "hours_j22_nu" ...
    "conference_submit_nu" "conference_accept_nu" "perma_hap_nu"];

dat1 = raw_data(:,vn1);
dat2 = raw_data(:,vn2);

dat2.Properties.VariableNames = vn1;

data = [dat1;dat2];

end